"""PapersStaging: idx PK + paper FK

Revision ID: 20260214_0001
Revises: e931ea39f86d
Create Date: 2026-02-14

"""
from __future__ import annotations

from alembic import op


# revision identifiers, used by Alembic.
revision = "20260214_0001"
down_revision = "e931ea39f86d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS soles.papers_staging (
            idx BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id UUID REFERENCES soles.papers(id) ON DELETE CASCADE,
            is_approved BOOLEAN NOT NULL DEFAULT FALSE,
            approval_timestamp TIMESTAMPTZ,
            title TEXT NOT NULL,
            authors TEXT[] NOT NULL DEFAULT '{}'::text[],
            journal TEXT,
            year INTEGER,
            abstract TEXT,
            pdf_url TEXT,
            ingestion_source TEXT,
            ingestion_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
            embedding vector(1024)
        );
        """
    )

    # In case the table already exists with NOT NULL, align it to the workflow.
    op.execute(
        """
        ALTER TABLE soles.papers_staging
        ALTER COLUMN id DROP NOT NULL;
        """
    )

    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_papers_staging_paper_id
        ON soles.papers_staging (id);
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_papers_staging_is_approved
        ON soles.papers_staging (is_approved);
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS soles.idx_papers_staging_is_approved")
    op.execute("DROP INDEX IF EXISTS soles.idx_papers_staging_paper_id")
    op.execute("DROP TABLE IF EXISTS soles.papers_staging")
