"""First alembic commit

Revision ID: a661a205fc45
Revises:
Create Date: 2026-02-14 22:39:46.220028

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = "a661a205fc45"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "papers",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "authors",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("journal", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("pdf_url", sa.Text(), nullable=True),
        sa.Column("ingestion_source", sa.Text(), nullable=True),
        sa.Column(
            "ingestion_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cr_soles",
    )
    op.create_table(
        "extractions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("extraction_version", sa.Text(), nullable=False),
        sa.Column(
            "metadata_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "study_design_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "sample_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "outcomes_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "risk_of_bias_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "extraction_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status IN ('success', 'partial', 'failed')", name="ck_extractions_status"
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["cr_soles.papers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cr_soles",
    )
    op.create_table(
        "agents_logs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("paper_id", sa.UUID(), nullable=True),
        sa.Column("extraction_id", sa.UUID(), nullable=True),
        sa.Column("agent_name", sa.Text(), nullable=False),
        sa.Column("raw_output", sa.Text(), nullable=True),
        sa.Column(
            "cleaned_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("input", sa.Text(), nullable=True),
        sa.Column("node_name", sa.Text(), nullable=True),
        sa.Column("prompt_hash", sa.Text(), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"], ["cr_soles.extractions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["cr_soles.papers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cr_soles",
    )
    op.create_table(
        "evaluations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("extraction_id", sa.UUID(), nullable=False),
        sa.Column("evaluator_id", sa.Text(), nullable=False),
        sa.Column(
            "agreement_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "evaluation_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"], ["cr_soles.extractions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cr_soles",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evaluations", schema="cr_soles")
    op.drop_table("agents_logs", schema="cr_soles")
    op.drop_table("extractions", schema="cr_soles")
    op.drop_table("papers", schema="cr_soles")
    # ### end Alembic commands ###
