"""Add papers_staging

Revision ID: c1cf20366dd8
Revises: a661a205fc45
Create Date: 2026-02-15 16:09:32.534295

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = "c1cf20366dd8"
down_revision = "a661a205fc45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "papers_staging",
        sa.Column("idx", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column(
            "is_approved", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("approval_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "authors",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("journal", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("pdf_url", sa.Text(), nullable=True),
        sa.Column("ingestion_source", sa.Text(), nullable=True),
        sa.Column(
            "ingestion_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True
        ),
        sa.ForeignKeyConstraint(["id"], ["cr_soles.papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("idx"),
        schema="cr_soles",
    )
    op.create_index(
        op.f("ix_cr_soles_papers_staging_id"),
        "papers_staging",
        ["id"],
        unique=False,
        schema="cr_soles",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cr_soles_papers_staging_id"),
        table_name="papers_staging",
        schema="cr_soles",
    )
    op.drop_table("papers_staging", schema="cr_soles")
    # ### end Alembic commands ###
