"""Add PapersStaging table

Revision ID: e931ea39f86d
Revises: 20260127_0001
Create Date: 2026-02-12 22:54:56.642561

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e931ea39f86d'
down_revision = '20260127_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_agents_logs_agent_name'), table_name='agents_logs', schema='soles')
    op.drop_index(op.f('idx_agents_logs_extraction_id'), table_name='agents_logs', schema='soles')
    op.drop_index(op.f('idx_agents_logs_node_name'), table_name='agents_logs', schema='soles')
    op.drop_index(op.f('idx_agents_logs_paper_id'), table_name='agents_logs', schema='soles')
    op.drop_index(op.f('idx_agents_logs_prompt_hash'), table_name='agents_logs', schema='soles')
    op.drop_index(op.f('idx_agents_logs_time'), table_name='agents_logs', schema='soles')
    op.drop_index(op.f('idx_evaluations_evaluator_id'), table_name='evaluations', schema='soles')
    op.drop_index(op.f('idx_evaluations_extraction_id'), table_name='evaluations', schema='soles')
    op.drop_index(op.f('idx_evaluations_time'), table_name='evaluations', schema='soles')
    op.drop_index(op.f('idx_extractions_paper_id'), table_name='extractions', schema='soles')
    op.drop_index(op.f('idx_extractions_paper_time'), table_name='extractions', schema='soles')
    op.drop_index(op.f('idx_extractions_status'), table_name='extractions', schema='soles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_extractions_status'), 'extractions', ['status'], unique=False, schema='soles')
    op.create_index(op.f('idx_extractions_paper_time'), 'extractions', ['paper_id', sa.literal_column('extraction_timestamp DESC')], unique=False, schema='soles')
    op.create_index(op.f('idx_extractions_paper_id'), 'extractions', ['paper_id'], unique=False, schema='soles')
    op.create_index(op.f('idx_evaluations_time'), 'evaluations', [sa.literal_column('evaluation_timestamp DESC')], unique=False, schema='soles')
    op.create_index(op.f('idx_evaluations_extraction_id'), 'evaluations', ['extraction_id'], unique=False, schema='soles')
    op.create_index(op.f('idx_evaluations_evaluator_id'), 'evaluations', ['evaluator_id'], unique=False, schema='soles')
    op.create_index(op.f('idx_agents_logs_time'), 'agents_logs', [sa.literal_column('timestamp DESC')], unique=False, schema='soles')
    op.create_index(op.f('idx_agents_logs_prompt_hash'), 'agents_logs', ['prompt_hash'], unique=False, schema='soles')
    op.create_index(op.f('idx_agents_logs_paper_id'), 'agents_logs', ['paper_id'], unique=False, schema='soles')
    op.create_index(op.f('idx_agents_logs_node_name'), 'agents_logs', ['node_name'], unique=False, schema='soles')
    op.create_index(op.f('idx_agents_logs_extraction_id'), 'agents_logs', ['extraction_id'], unique=False, schema='soles')
    op.create_index(op.f('idx_agents_logs_agent_name'), 'agents_logs', ['agent_name'], unique=False, schema='soles')
    # ### end Alembic commands ###
